# Generated by Django 4.1.1 on 2023-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0007_alter_hotels_country_alter_hotels_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='touristguide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_place', models.CharField(max_length=250)),
                ('guide_img', models.ImageField(upload_to='pics')),
                ('guide_desc', models.TextField()),
                ('guide_price', models.TextField()),
            ],
        ),
    ]
