# Generated by Django 4.1.1 on 2023-02-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0008_touristguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='touristguide',
        ),
    ]
