# Generated by Django 4.1.1 on 2023-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0009_delete_touristguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_place', models.CharField(max_length=250)),
                ('package_img', models.ImageField(upload_to='pics')),
                ('package_desc', models.TextField()),
                ('package_price', models.TextField()),
            ],
        ),
    ]
