# Generated by Django 4.1.1 on 2023-02-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0010_packages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='packages',
        ),
    ]
