# Generated by Django 4.1.1 on 2023-03-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0011_delete_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250)),
                ('package_place', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('package_price', models.TextField()),
            ],
        ),
    ]
